#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-S-2.0
# Copyright 2026 Romain Dolbeau
# Source location: https://github.com/MelkhiorVintageComputing/RD68884

"""The vectors of sim/programs/fpu_m5.S, from the golden model.

    python3 sim/programs/gen_fpu_m5.py OUT.S [N] [SEED]

The operands are drawn as tools/iss/tests/test_arith.py draws them. The
wanted results come from tools/model/arith.py: the instruction on FP1 (and
FP2), then FMOVE.X FP1 with FPCR = 0 for the dump the program compares.
sim/programs/gen_fpu_m6.py uses the same record() and write().
"""

import random
import sys

from model import arith as A, formats as F
from iss.tests.test_arith import IN_FMTS, OUT_FMTS, x_operand, near, source, fpcr

PATTERN = 0xA5C3E187
# M5's operations; M6's are in gen_fpu_m6.py.
OPS = [0x00, 0x01, 0x03, 0x04, 0x18, 0x1A, 0x1E, 0x1F, 0x20, 0x22, 0x23, 0x24,
       0x27, 0x28, 0x38, 0x3A, 0x05, 0x1B, 0x2B, 0x39, 0x3D]


def cmd(opclass, rx, ry, ext):
    return (opclass << 13) | (rx << 10) | (ry << 7) | ext


def record(c, dst, src_bytes, fc, image=None, kreg=None):
    """The 60-byte record of one vector: what pre loads, and what post
    must find (sim/programs/fpu_m5.S)."""
    # What pre does: FMOVE.X in, with FPCR = 0, normalises as any load does.
    st = A.State()
    for r, img in ((1, dst), (2, int.from_bytes(src_bytes, 'big'))):
        A.apply(st, A.general(st, cmd(2, F.FMT_X, r, 0), img))
    st.fpcr, st.fpsr = fc, 0
    res = A.general(st, c, image, kreg)
    A.apply(st, res)
    vec = A.trap_vector(res.exc, st.enable) or 0
    fpsr = st.fpsr

    obuf = [PATTERN] * 3
    if res.mem is not None:
        n = res.mem_bytes
        b = res.mem.to_bytes(n, 'big') + (PATTERN.to_bytes(4, 'big') * 3)[n:]
        obuf = [int.from_bytes(b[4 * i:4 * i + 4], 'big') for i in range(3)]

    st.fpcr = 0
    dump = A.general(st, cmd(3, F.FMT_X, 1, 0), None).mem
    return dst.to_bytes(12, 'big') + src_bytes + fc.to_bytes(4, 'big') \
        + dump.to_bytes(12, 'big') + b''.join(w.to_bytes(4, 'big') for w in obuf) \
        + fpsr.to_bytes(4, 'big') + vec.to_bytes(4, 'big')


def vector(rng):
    """(code lines before pre, the instruction's words, record)."""
    dst = x_operand(rng)
    fc = fpcr(rng)
    k = rng.randrange(10)
    if k < 4:
        rx = rng.choice([1, 2])
        src_x = near(rng, dst) if rx == 2 and rng.randrange(3) == 0 else x_operand(rng)
        c = cmd(0, rx, 1, rng.choice(OPS))
        return [], [0xF200, c], record(c, dst, src_x.to_bytes(12, 'big'), fc)
    if k < 8:
        fmt = rng.choice(IN_FMTS)
        img, n = source(rng, fmt)
        c = cmd(2, fmt, 1, rng.choice(OPS))
        src = img.to_bytes(n, 'big') + bytes(12 - n)
        return [], [0xF22A, c, 12], record(c, dst, src, fc, img)           # (12,A2)
    fmt = rng.choice(OUT_FMTS)
    c = cmd(3, fmt, 1, 0)
    return [], [0xF213, c], record(c, dst, x_operand(rng).to_bytes(12, 'big'), fc)  # (A3)


def write(out, vecs):
    code, data = [], []
    for i, (pre, words, rec) in enumerate(vecs):
        code.append(''.join(f'        {line}\n' for line in pre)
                    + f'        lea     v{i}, %a2\n        bsr     pre\n'
                    f'        .word   {", ".join(f"0x{w:04X}" for w in words)}\n'
                    f'        bsr     post\n')
        data.append(f'v{i}:    .byte   {", ".join(f"0x{b:02X}" for b in rec)}\n')
    with open(out, 'w') as fh:
        fh.write(f'| GENERATED by {sys.argv[0]}. Do not edit.\n')
        fh.write(''.join(code))
        fh.write('        bra     vec_end\n        .even\n')
        fh.write(''.join(data))
        fh.write('vec_end:\n')


def main():
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 150
    rng = random.Random(int(sys.argv[3]) if len(sys.argv) > 3 else 5)
    write(sys.argv[1], [vector(rng) for _ in range(n)])


if __name__ == '__main__':
    main()
