#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-S-2.0
# Copyright 2026 Romain Dolbeau
# Source location: https://github.com/MelkhiorVintageComputing/RD68884

"""The micro-assembler.

    python3 tools/ucode/asm.py           # regenerate rtl/gen/ and build/ucode*.json
    python3 tools/ucode/asm.py --check   # fail if rtl/gen/ is stale

The program is assembled twice, once per model (doc/rd68885.md): the MC68881
(RD68884) and the MC68882 (RD68885). program.build(model) sees the model as
p.model; the field table and the constant ROM are shared.

The program (tools/ucode/program.py) is Python: L('label') places a label,
u(SEQ='BR', COND='CMD_PEND', IMM='cmd', ...) one microinstruction, and
table('name', bits, {index: 'label'}, default='label') a jump table for DISP,
placed at an address whose low `bits` bits are zero. IMM may be a label.

Outputs:
  rtl/gen/rd68884_ucode_pkg.sv   field positions, enumerations, entry points
                                 (ENTRY_* for the MC68881, ENTRY82_* for the
                                 MC68882)
  rtl/gen/rd68884_ucode_rom.sv   the store, a registered case ROM indexed only
                                 by the address bits in use (the RD68021
                                 technique: Quartus builds a sparse case from
                                 logic)
  rtl/gen/rd68884_crom.sv        the constant ROM (tools/ucode/crom.py)
  rtl/gen/rd68885_ucode_rom.sv   the MC68882's store, the same way
  build/ucode.json               the words, labels and comments, and the
                                 constant ROM, for the ISS (ucode-68882.json:
                                 the MC68882's)
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import fields  # noqa: E402
import crom  # noqa: E402

ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
GEN = os.path.join(ROOT, 'rtl', 'gen')

BANNER = """// SPDX-License-Identifier: CERN-OHL-S-2.0
// Copyright 2026 Romain Dolbeau
// Source location: https://github.com/MelkhiorVintageComputing/RD68884

// GENERATED by tools/ucode/asm.py from tools/ucode/fields.py and
// tools/ucode/program.py. Do not edit; `make ucode` rewrites it and
// `make ucode-check` fails if it is stale.
"""


class Program:
    def __init__(self, model=68881):
        self.model = model      # 68881 or 68882: which program to emit
        self.code = []          # (fields dict, comment, labels at this word)
        self.pending = []
        self.tables = []        # (name, bits, mapping, default)

    def L(self, name):
        self.pending.append(name)

    def u(self, comment='', **f):
        self.code.append((f, comment, self.pending))
        self.pending = []

    def table(self, name, bits, mapping, default):
        self.tables.append((name, bits, mapping, default))

    # -------------------------------------------------------------- assembly
    def assemble(self):
        assert not self.pending, f'labels at the end: {self.pending}'
        labels = {}
        words = []                              # (fields, comment)
        for f, c, labs in self.code:
            for name in labs:
                assert name not in labels, f'label {name} twice'
                labels[name] = len(words)
            words.append((f, c))
        # Tables after the code, each aligned to its size.
        for name, bits, mapping, default in self.tables:
            size = 1 << bits
            base = (len(words) + size - 1) // size * size
            while len(words) < base:
                words.append(({'SEQ': 'JUMP', 'TGT': 'illegal'}, 'padding'))
            assert name not in labels
            labels[name] = base
            for i in range(size):
                tgt = mapping.get(i, default)
                words.append(({'SEQ': 'JUMP', 'TGT': tgt}, f'{name}[{i}] -> {tgt}'))
        assert len(words) <= 1 << fields.UADDR_BITS, 'microcode store full'
        lay, width = fields.layout()
        out = []
        for i, (f, c) in enumerate(words):
            w = 0
            for name, pos, wid, vals in lay:
                v = f.get(name, 0)
                if isinstance(v, str):
                    if isinstance(vals, list) and v in vals:
                        v = vals.index(v)
                    elif v in labels:
                        v = labels[v]
                    else:
                        raise ValueError(f'word {i}: {name}={v!r} unknown')
                assert 0 <= v < (1 << wid), f'word {i}: {name}={v} too wide'
                w |= v << pos
            for k in f:
                assert k in [x[0] for x in lay], f'word {i}: no field {k}'
            out.append((w, c))
        return out, labels, width


# -----------------------------------------------------------------------------
# Generators
# -----------------------------------------------------------------------------
ENTRIES = ['reset', 'abort', 'restore', 'illegal']


def gen_pkg(labels, width, labels82=None):
    lay, _ = fields.layout()
    o = [BANNER, '// The microword layout and the micro-addresses the sequencer jumps to', '// by itself (doc/microcode.md).', '',
         'package rd68884_ucode_pkg;', '']
    o.append(f'  localparam int UW = {width};')
    o.append(f'  localparam int UA = {fields.UADDR_BITS};')
    o.append('')
    for name, pos, wid, vals in lay:
        o.append(f'  localparam int F_{name}_LSB = {pos};')
        o.append(f'  localparam int F_{name}_W   = {wid};')
        if isinstance(vals, list):
            for i, v in enumerate(vals):
                o.append(f"  localparam logic [{wid - 1}:0] {name}_{v} = {wid}'d{i};")
        o.append('')
    for e in ENTRIES:
        o.append(f"  localparam logic [{fields.UADDR_BITS - 1}:0] ENTRY_{e.upper()} = "
                 f"{fields.UADDR_BITS}'d{labels[e]};")
    if labels82 is not None:
        o.append('  // The MC68882 program (RD68885)')
        for e in ENTRIES:
            o.append(f"  localparam logic [{fields.UADDR_BITS - 1}:0] ENTRY82_{e.upper()} = "
                     f"{fields.UADDR_BITS}'d{labels82[e]};")
    o += ['', 'endpackage', '']
    return '\n'.join(o)


def gen_rom(words, labels, width, name='rd68884_ucode_rom', what=''):
    ua = fields.UADDR_BITS
    iw = max(1, (len(words) - 1).bit_length())
    hw = (width + 3) // 4
    illegal = words[labels['illegal']][0]
    o = [BANNER, f"""// The {what}microcode store, {len(words)} words of {width} bits.
//
// Read at `addr`, which the sequencer drives with the NEXT micro-address, and
// registered, so the word arrives with the micro-address it belongs to.
//
// The read register has no reset: a block RAM keeps it inside the primitive and
// cannot give it a reset value on every part (Quartus, given one, builds the
// store from logic). It is reset-EQUIVALENT: while rst_n is low the address is
// forced to the reset entry, so the register holds the reset word from the first
// clock edge in reset. tools/reset_audit.py names it as the one exemption.
//
// Indexed by the low {iw} bits only; a higher micro-address -- reachable by no
// program path -- selects the illegal entry through a flag registered with the
// read, so the function is that of the full case (the RD68021 technique).
module {name} (
    input  logic          clk,
    input  logic          rst_n,
    input  logic [{ua - 1}:0]   addr,
    output logic [{width - 1}:0]  uw
);

  logic [{ua - 1}:0] a;
  assign a = rst_n ? addr : {ua}'d{labels['reset']};

  (* rom_style = "block" *)
  logic [{width - 1}:0] rom_q;
"""]
    if iw < ua:
        o.append(f"""  logic hi, hi_q;
  assign hi = |a[{ua - 1}:{iw}];
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) hi_q <= 1'b0;
    else        hi_q <= hi;
  end
  assign uw = hi_q ? {width}'h{illegal:0{hw}X} : rom_q;

  always_ff @(posedge clk) begin
    case (a[{iw - 1}:0])""")
    else:
        o.append("""  assign uw = rom_q;

  always_ff @(posedge clk) begin
    case (a)""")
    lw = iw if iw < ua else ua
    for i, (w, c) in enumerate(words):
        cc = c.replace('\n', ' ')
        o.append(f"      {lw}'d{i:<5}: rom_q <= {width}'h{w:0{hw}X};" + (f'   // {cc}' if cc else ''))
    o.append(f"""      default:  rom_q <= {width}'h{illegal:0{hw}X};
    endcase
  end

endmodule
""")
    return '\n'.join(o)


def gen_crom(table):
    aw = (crom.DEPTH - 1).bit_length()
    hw = (crom.WIDTH + 3) // 4
    o = [BANNER.replace('tools/ucode/program.py', 'tools/ucode/crom.py'), f"""// The constant ROM, {crom.DEPTH} entries of {{sticky, sign, exponent[17:0],
// mantissa[71:0]}}: the FMOVECR constants and the powers of ten, each
// truncated to 72 bits with a sticky bit for what was cut off
// (tools/ucode/crom.py, doc/microcode.md).
//
// Read with `re` and registered, as the register file is: a block RAM on every
// target. The read register has no reset, and nothing reads it before the
// microcode has issued a read: the third exemption in tools/reset_audit.py.
module rd68884_crom (
    input  logic              clk,
    input  logic              re,
    input  logic [{aw - 1}:0]       addr,
    output logic [{crom.WIDTH - 1}:0]      q
);

  (* rom_style = "block" *)
  logic [{crom.WIDTH - 1}:0] rom_q;
  assign q = rom_q;

  always_ff @(posedge clk) begin
    if (re) begin
      case (addr)"""]
    zero = crom.word(crom.ZERO)
    for i, e in enumerate(table):
        w = crom.word(e)
        if w != zero:
            o.append(f"        {aw}'d{i:<4}: rom_q <= {crom.WIDTH}'h{w:0{hw}X};")
    o.append(f"""        default: rom_q <= {crom.WIDTH}'h{zero:0{hw}X};
      endcase
    end
  end

endmodule
""")
    return '\n'.join(o)


def build(model=68881):
    sys.path.insert(0, HERE)
    import program  # noqa: E402
    p = program.build(model)
    words, labels, width = p.assemble()
    for e in ENTRIES:
        assert e in labels, f'no entry point {e}'
    return words, labels, width


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    words, labels, width = build(68881)
    words82, labels82, width82 = build(68882)
    assert width82 == width
    files = {os.path.join(GEN, 'rd68884_ucode_pkg.sv'): gen_pkg(labels, width, labels82),
             os.path.join(GEN, 'rd68884_ucode_rom.sv'): gen_rom(words, labels, width),
             os.path.join(GEN, 'rd68885_ucode_rom.sv'):
                 gen_rom(words82, labels82, width, 'rd68885_ucode_rom', 'MC68882 (RD68885) ')}
    ctab = crom.entries()
    files[os.path.join(GEN, 'rd68884_crom.sv')] = gen_crom(ctab)
    os.makedirs(os.path.join(ROOT, 'build'), exist_ok=True)
    for fn, (w_, l_) in (('ucode.json', (words, labels)), ('ucode-68882.json', (words82, labels82))):
        with open(os.path.join(ROOT, 'build', fn), 'w') as fh:
            json.dump({'width': width, 'words': [w for w, _ in w_],
                       'comments': [c for _, c in w_], 'labels': l_,
                       'crom': [list(e) for e in ctab]}, fh)
    if a.check:
        stale = [f for f, t in files.items()
                 if not os.path.exists(f) or open(f).read() != t]
        if stale:
            print('FAIL: ucode-check, stale: ' + ' '.join(os.path.relpath(f, ROOT) for f in stale))
            return 1
        print(f'  ucode: {len(words)} words (MC68882: {len(words82)}) of {width} bits, generated files current')
        return 0
    os.makedirs(GEN, exist_ok=True)
    for f, t in files.items():
        with open(f, 'w') as fh:
            fh.write(t)
    print(f'  ucode: {len(words)} words (MC68882: {len(words82)}) of {width} bits')
    return 0


if __name__ == '__main__':
    sys.exit(main())
