#!/usr/bin/env python3
# SPDX-License-Identifier: CERN-OHL-S-2.0
# Copyright 2026 Romain Dolbeau
# Source location: https://github.com/MelkhiorVintageComputing/RD68884

"""Pin constraints for a board, from its LiteX platform file (doc/boards.md).

    python3 tools/board_pins.py PLATFORM.py OUT.xdc

The platform file is the board's own definition and stays where it is
(Inputs/ is immutable). LiteX is not installed here, so its modules are
replaced by stubs that only record what the platform declares; then every port
of the board top in PORTS gets its PACKAGE_PIN and IOSTANDARD from the
platform's (name, index) resource. A port the platform does not have is an
error, so the constraints can never silently miss a pin.
"""

import sys
import types

# The IIsiA7 Mini top's ports (boards/iisia7_mini/rd68884_iisia7_top.sv):
# port -> list of (resource, index, subsignal or None), concatenated in order
# for a vector port.
PORTS = {
    'clk100':      [('clk100', 0, None)],
    'A_3v3':       [('A_3v3', 0, None)],
    'fc_3v3':      [('fc_3v3', 0, None)],
    'as_3v3_n':    [('as_3v3_n', 0, None)],
    'ds_3v3_n':    [('ds_3v3_n', 0, None)],
    'rw_3v3_n':    [('rw_3v3_n', 0, None)],
    'reset_3v3_n': [('reset_3v3_n', 0, None)],
    'D_3v3':       [('D_3v3', 0, None)],
    'dsack_3v3_n': [('dsack_3v3_n', 0, None)],
    'halt_3v3_n':  [('halt_3v3_n', 0, None)],
    'user_leds':   [('user_leds', 0, None), ('user_leds', 1, None)],
}


class Pins:
    def __init__(self, *s):
        self.pins = ' '.join(s).split()


class IOStandard:
    def __init__(self, name):
        self.name = name


class Misc:
    def __init__(self, misc):
        self.misc = misc


class Subsignal:
    def __init__(self, name, *items):
        self.name, self.items = name, items


class _Platform:
    def __init__(self, *a, **k):
        self.toolchain = types.SimpleNamespace()

    def add_platform_command(self, *a, **k):
        pass

    def add_extension(self, io):
        _EXTENSIONS.append(io)


_EXTENSIONS = []


def _stub_litex():
    """Install stand-ins for the litex modules the platform imports."""
    gp = types.ModuleType('litex.build.generic_platform')
    for n, v in (('Pins', Pins), ('IOStandard', IOStandard), ('Misc', Misc),
                 ('Subsignal', Subsignal)):
        setattr(gp, n, v)
    gp.__all__ = ['Pins', 'IOStandard', 'Misc', 'Subsignal']
    xil = types.ModuleType('litex.build.xilinx')
    xil.XilinxPlatform = _Platform
    ocd = types.ModuleType('litex.build.openocd')
    ocd.OpenOCD = object
    for name, mod in (('litex', types.ModuleType('litex')),
                      ('litex.build', types.ModuleType('litex.build')),
                      ('litex.build.generic_platform', gp),
                      ('litex.build.xilinx', xil), ('litex.build.openocd', ocd)):
        sys.modules[name] = mod


def resources(platform_py):
    """{(name, index): (pins, iostandard, misc)} for every resource the
    platform declares, its own and the extensions the Platform class adds."""
    _stub_litex()
    ns = {'__name__': 'platform'}
    exec(compile(open(platform_py).read(), platform_py, 'exec'), ns)
    ns['Platform']()                     # adds the PDS extension
    out = {}
    for io in [ns['_io']] + _EXTENSIONS:
        for entry in io:
            name, index, items = entry[0], entry[1], entry[2:]
            pins = [x for x in items if isinstance(x, Pins)]
            std = [x.name for x in items if isinstance(x, IOStandard)]
            misc = [x.misc for x in items if isinstance(x, Misc)]
            if pins:
                out[(name, index)] = (pins[0].pins, std[0] if std else None, misc)
    return out


def main():
    platform_py, out = sys.argv[1], sys.argv[2]
    res = resources(platform_py)
    lines = [f'# Generated by tools/board_pins.py from {platform_py}; do not edit.']
    for port, parts in PORTS.items():
        pins = []
        for name, index, _ in parts:
            if (name, index) not in res:
                sys.exit(f'board_pins: the platform has no ({name!r}, {index})')
            p, std, misc = res[(name, index)]
            pins += [(x, std, misc) for x in p]
        vector = len(pins) > 1 or port in ('A_3v3', 'fc_3v3', 'D_3v3', 'dsack_3v3_n', 'user_leds')
        for i, (pin, std, misc) in enumerate(pins):
            target = f'{port}[{i}]' if vector else port
            lines.append(f'set_property -dict {{PACKAGE_PIN {pin} IOSTANDARD {std.upper()}}} '
                         f'[get_ports {{{target}}}]')
            for m in misc:
                key, _, val = m.partition(' ')
                lines.append(f'set_property {key} {val.upper()} [get_ports {{{target}}}]')
    open(out, 'w').write('\n'.join(lines) + '\n')
    print(f'  board_pins: {len(lines) - 1} pins from {platform_py}')


if __name__ == '__main__':
    main()
